module.exports = {
    externals: {
        electron: 'commonjs electron',
        ipc: 'commonjs ipc',
        'ipc-renderer': 'commonjs ipc-renderer',
        remote: 'commonjs remote',
        fs: 'commonjs fs',
        assert: 'commonjs assert',
        crypto: 'commonjs crypto',
        http: 'commonjs http',
        https: 'commonjs https',
        os: 'commonjs os',
        path: 'commonjs path',
        readline: 'commonjs readline',
        stream: 'commonjs stream',
        timers: 'commonjs timers',
        url: 'commonjs url',
        util: 'commonjs util',
        constants: 'commonjs constants',
        net: 'commonjs net',
        zlib: 'commonjs zlib',
        querystring: 'commonjs querystring',
    },
};
